"""
This code a slight modification of perplexity by hugging face
https://huggingface.co/docs/transformers/perplexity

Both this code and the orignal code are published under the MIT license.

by Burhan Ul tayyab and Nicholas Chua
"""

import logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logging.getLogger("httpx").setLevel(logging.WARNING)

import math
import os
import torch
import re
import nltk
from transformers import GPT2LMHeadModel, GPT2TokenizerFast
from collections import OrderedDict
from typing import Tuple, Dict, Union, Optional, List
from pathlib import Path

from config import settings

logger = logging.getLogger(__name__)

class GPT2PPL:
    def __init__(self, device: Optional[torch.device] = None) -> None:
        if hasattr(self, "model"):
            return
        if device is None:
            device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
        self.device: torch.device = device
        self.model_id: str = settings.model_id
        self.model: GPT2LMHeadModel = GPT2LMHeadModel.from_pretrained(settings.model_id).to(device)
        self.tokenizer: GPT2TokenizerFast = GPT2TokenizerFast.from_pretrained(settings.model_id)

        self.max_length: int = settings.max_length or self.model.config.n_positions
        self.stride: int = settings.stride
        self.low_threshold: int = settings.low_threshold
        self.high_threshold: int = settings.high_threshold

        self.calibration_midpoint: Optional[float] = None
        self.calibration_scale: Optional[float] = None

        if settings.human_text_file and settings.ai_text_file:
            self._calibrate(settings.human_text_file, settings.ai_text_file)
    def getResults(self, threshold: float) -> Tuple[str, float]:
        if self.calibration_midpoint is not None and self.calibration_scale is not None:
            confidence: float = self._sigmoid(threshold, self.calibration_midpoint, self.calibration_scale)
        else:
            midpoint: float = self.high_threshold
            scale: float = midpoint * 0.14 or 10.0
            confidence: float = self._sigmoid(threshold, midpoint, scale)

        if confidence < 0.5:
            label_text = f"The Text is generated by AI."
        elif confidence < 0.7:
            label_text = "The Text is most probably contain parts which are generated by AI. (require more text for better Judgement)"
        else:
            label_text = "The Text is written by Human."
        label_text += f'\n- {100*(1-confidence):.2f}% Confident Text is AI'

        return label_text, confidence

    def _calibrate(self, human_file: str, ai_file: str) -> None:
        script_dir = Path(__file__).parent
        human_file_path = script_dir / human_file
        ai_file_path = script_dir / ai_file
    
        if not os.path.exists(human_file_path) or not os.path.exists(ai_file_path):
            logger.warning("Calibration files not found, skipping calibration")
            self.calibration_midpoint: float = self.high_threshold
            self.calibration_scale: float = self.high_threshold * 0.14 or 10.0
            return

        logger.info("Calibrating thresholds from validation files...")
        human_ppls: List[float] = []
        ai_ppls: List[float] = []

        try:
            with open(human_file_path, "r", encoding="utf-8") as f:
                text = f.read().strip()
                if text:
                    lines = nltk.sent_tokenize(text)
                    for line in lines:
                        if re.search("[a-zA-Z0-9]+", line):
                            line = line.strip()
                            try:
                                ppl = self.getPPL(line)
                                human_ppls.append(ppl)
                            except Exception:
                                continue

            with open(ai_file_path, "r", encoding="utf-8") as f:
                text = f.read().strip()
                if text:
                    lines = nltk.sent_tokenize(text)
                    for line in lines:
                        if re.search("[a-zA-Z0-9]+", line):
                            line = line.strip()
                            try:
                                ppl = self.getPPL(line)
                                ai_ppls.append(ppl)
                            except Exception:
                                continue

            if human_ppls and ai_ppls:
                mean_human = sum(human_ppls) / len(human_ppls)
                mean_ai = sum(ai_ppls) / len(ai_ppls)
                std_human = (sum((x - mean_human) ** 2 for x in human_ppls) / len(human_ppls)) ** 0.5
                std_ai = (sum((x - mean_ai) ** 2 for x in ai_ppls) / len(ai_ppls)) ** 0.5

                self.calibration_midpoint = (mean_human + mean_ai) / 2
                self.calibration_scale = (std_human + std_ai) / 2 or 10.0
                logger.info("Calibration complete: midpoint=%.2f, scale=%.2f", self.calibration_midpoint, self.calibration_scale)
            else:
                logger.warning("Insufficient calibration data, using default calibration")
                self.calibration_midpoint = self.high_threshold
                self.calibration_scale = self.high_threshold * 0.14 or 10.0
        except Exception as e:
            logger.error("Calibration failed: %s", str(e))
            self.calibration_midpoint = self.high_threshold
            self.calibration_scale = self.high_threshold * 0.14 or 10.0

    def _sigmoid(self, x: float, midpoint: float, scale: float) -> float:
        return 1.0 / (1.0 + math.exp(-(x - midpoint) / scale))

    def __call__(self, sentence: str) -> Tuple[Dict[str, Union[float, int]], str]:
        """
        Takes in a sentence split by full stop
        and print the perplexity of the total sentence

        split the lines based on full stop and find the perplexity of each sentence and print
        average perplexity

        Burstiness is the max perplexity of each sentence
        """
        results: OrderedDict = OrderedDict()

        if not sentence or not isinstance(sentence, str):
            return {"error": "Invalid input: sentence must be a non-empty string."}, "Invalid input"

        try:
            total_valid_char: List[str] = re.findall("[a-zA-Z0-9]+", sentence)
            total_char_cnt: int = sum([len(x) for x in total_valid_char])
        except re.error as e:
            logger.error("Regex error: %s", str(e))
            return {"error": "Error processing input text."}, "Error processing input text."

        fake_token_count: float = total_char_cnt * settings.char_to_token_ratio
        
        if fake_token_count < settings.minimum_tokens:
            return {"status": f"Please input more text (min {settings.minimum_tokens} tokens, current: {int(fake_token_count)})"}, f"Please input more text (min {settings.minimum_tokens} tokens, current: {int(fake_token_count)})"

        lines: List[str] = []
        try:
            lines = nltk.sent_tokenize(sentence)
        except Exception as e:
            logger.error("NLTK tokenization error: %s", str(e))
            lines = sentence.split(".")

        lines = [line.strip() for line in lines if line.strip()]

        try:
            ppl: int = self.getPPL(sentence)
        except Exception as e:
            logger.error("Error computing perplexity: %s", str(e))
            ppl: int = 0

        logger.debug("Perplexity %d", ppl)
        results["Perplexity"] = ppl

        offset: str = ""
        Perplexity_per_line: List[int] = []
        for i, line in enumerate(lines):
            if re.search("[a-zA-Z0-9]+", line) is None:
                continue
            # remove leading/trailing whitespace
            line = line.strip()
            try:
                ppl = self.getPPL(line)
                Perplexity_per_line.append(ppl)
            except Exception as e:
                logger.warning("Skipping line %d due to error: %s", i, str(e))
                continue

        if len(Perplexity_per_line) > 0:
            avg_per_line: float = sum(Perplexity_per_line) / len(Perplexity_per_line)
            max_per_line: float = max(Perplexity_per_line)
            logger.debug("Perplexity per line %.2f", avg_per_line)
            results["Perplexity per line"] = avg_per_line
            logger.debug("Burstiness %d", max_per_line)
            results["Burstiness"] = max_per_line
        else:
            results["Perplexity per line"] = 0
            results["Burstiness"] = 0

        out: str = ""
        confidence: float = 0.0
        try:
            out, confidence = self.getResults(results["Perplexity per line"])
        except Exception as e:
            logger.error("Error getting results: %s", str(e))
            out = "Error determining result"
        results["Human Confidence"] = confidence

        return results, out

    def getPPL(self, sentence: str) -> int:
        encodings: GPT2TokenizerFast.BatchEncoding = self.tokenizer(sentence, return_tensors="pt")
        seq_len: int = encodings.input_ids.size(1)

        nlls: List[torch.Tensor] = []
        likelihoods: List[torch.Tensor] = []
        prev_end_loc: int = 0
        for begin_loc in range(0, seq_len, self.stride):
            end_loc: int = min(begin_loc + self.max_length, seq_len)
            trg_len: int = end_loc - prev_end_loc
            input_ids: torch.Tensor = encodings.input_ids[:, begin_loc:end_loc].to(self.device)
            target_ids: torch.Tensor = input_ids.clone()
            target_ids[:, :-trg_len] = -100

            with torch.no_grad():
                outputs = self.model(input_ids, labels=target_ids)
                neg_log_likelihood: torch.Tensor = outputs.loss * trg_len
                likelihoods.append(neg_log_likelihood)

            nlls.append(neg_log_likelihood)

            prev_end_loc = end_loc
            if end_loc == seq_len:
                break
        ppl: float = float(torch.exp(torch.stack(nlls).sum() / end_loc))
        return ppl