"""
This code a slight modification of perplexity by hugging face
https://huggingface.co/docs/transformers/perplexity

Both this code and the orignal code are published under the MIT license.

by Burhan Ul tayyab and Nicholas Chua
"""

import logging
import torch
import re
import nltk
from transformers import GPT2LMHeadModel, GPT2TokenizerFast
from collections import OrderedDict
from typing import Tuple, Dict, Union, Optional, List

from config import settings

logger = logging.getLogger(__name__)


class GPT2PPL:
    def __init__(self, device: Optional[torch.device] = None) -> None:
        if device is None:
            device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
        self.device: torch.device = device
        self.model_id: str = settings.model_id
        self.model: GPT2LMHeadModel = GPT2LMHeadModel.from_pretrained(settings.model_id).to(device)
        self.tokenizer: GPT2TokenizerFast = GPT2TokenizerFast.from_pretrained(settings.model_id)

        self.max_length: int = settings.max_length or self.model.config.n_positions
        self.stride: int = settings.stride
        self.low_threshold: int = settings.low_threshold
        self.high_threshold: int = settings.high_threshold
        
    def getResults(self, threshold: float) -> Tuple[str, int]:
        if threshold < self.low_threshold:
            label: int = 0
            return "The Text is generated by AI.", label
        elif threshold < self.high_threshold:
            label: int = 0
            return "The Text is most probably contain parts which are generated by AI. (require more text for better Judgement)", label
        else:
            label: int = 1
            return "The Text is written by Human.", label

    def __call__(self, sentence: str) -> Tuple[Dict[str, Union[float, int]], str]:
        """
        Takes in a sentence split by full stop
        and print the perplexity of the total sentence

        split the lines based on full stop and find the perplexity of each sentence and print
        average perplexity

        Burstiness is the max perplexity of each sentence
        """
        results: OrderedDict = OrderedDict()

        total_valid_char = re.findall("[a-zA-Z0-9]+", sentence)
        total_valid_char = sum([len(x) for x in total_valid_char]) # finds len of all the valid characters a sentence

        fake_token_count: float = total_valid_char * settings.char_to_token_ratio
        
        if fake_token_count < settings.minimum_tokens:
            return {"status": f"Please input more text (min {settings.minimum_tokens} tokens, current: {int(fake_token_count)})"}, f"Please input more text (min {settings.minimum_tokens} tokens, current: {int(fake_token_count)})"

        lines: List[str] = nltk.sent_tokenize(sentence)
        lines = [line.strip() for line in lines if line.strip()]

        ppl: int = self.getPPL(sentence)
        logger.debug("Perplexity %d", ppl)
        results["Perplexity"] = ppl

        offset: str = ""
        Perplexity_per_line: List[int] = []
        for i, line in enumerate(lines):
            if re.search("[a-zA-Z0-9]+", line) == None:
                continue
            # remove leading/trailing whitespace
            line = line.strip()
            ppl = self.getPPL(line)
            Perplexity_per_line.append(ppl)

        if len(Perplexity_per_line) > 0:
            avg_per_line: float = sum(Perplexity_per_line)/len(Perplexity_per_line)
            max_per_line: int = max(Perplexity_per_line)
            logger.debug("Perplexity per line %.2f", avg_per_line)
            results["Perplexity per line"] = avg_per_line
            logger.debug("Burstiness %d", max_per_line)
            results["Burstiness"] = max_per_line
        else:
            results["Perplexity per line"] = 0
            results["Burstiness"] = 0

        out: str
        label: int
        out, label = self.getResults(results["Perplexity per line"])
        results["label"] = label

        return results, out

    def getPPL(self, sentence: str) -> int:
        encodings = self.tokenizer(sentence, return_tensors="pt")
        seq_len: int = encodings.input_ids.size(1)

        nlls: List[torch.Tensor] = []
        likelihoods: List[torch.Tensor] = []
        prev_end_loc: int = 0
        for begin_loc in range(0, seq_len, self.stride):
            end_loc: int = min(begin_loc + self.max_length, seq_len)
            trg_len: int = end_loc - prev_end_loc
            input_ids: torch.Tensor = encodings.input_ids[:, begin_loc:end_loc].to(self.device)
            target_ids: torch.Tensor = input_ids.clone()
            target_ids[:, :-trg_len] = -100

            with torch.no_grad():
                outputs = self.model(input_ids, labels=target_ids)
                neg_log_likelihood: torch.Tensor = outputs.loss * trg_len
                likelihoods.append(neg_log_likelihood)

            nlls.append(neg_log_likelihood)

            prev_end_loc = end_loc
            if end_loc == seq_len:
                break
        ppl: int = int(torch.exp(torch.stack(nlls).sum() / end_loc))
        return ppl